'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Data

    Partial Public Class AlrahmaCharity
        Public Property ID As Integer
        Public Property ProjectName As String
        Public Property Description As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property Priority As Nullable(Of Integer)
        Public Property Service As String
    
        Public Overridable Property AlrahmaCharityTransactions As ICollection(Of AlrahmaCharityTransaction) = New HashSet(Of AlrahmaCharityTransaction)
        Public Overridable Property CharitySubProjects As ICollection(Of CharitySubProject) = New HashSet(Of CharitySubProject)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class AlrahmaCharityTransaction
        Public Property ID As Integer
        Public Property ProjectID As Nullable(Of Integer)
        Public Property MobileNumber As String
        Public Property EmailID As String
        Public Property Amount As String
        Public Property TransactionStatus As String
        Public Property TrackID As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property Service As String
        Public Property SubprojectId As Nullable(Of Integer)
    
        Public Overridable Property AlrahmaCharity As AlrahmaCharity
        Public Overridable Property CharitySubProject As CharitySubProject
    
    End Class

End Namespace
Namespace Data

    Partial Public Class balance
        Public Property id As Integer
        Public Property message As String
        Public Property [date] As Date
    
    End Class

End Namespace
Namespace Data

    Partial Public Class CharitySubProject
        Public Property ID As Integer
        Public Property ProjectType As Nullable(Of Integer)
        Public Property ProjectID As Nullable(Of Integer)
        Public Property SubprojectName As String
        Public Property Description As String
        Public Property Status As Nullable(Of Boolean)
        Public Property Priority As Nullable(Of Integer)
    
        Public Overridable Property AlrahmaCharity As AlrahmaCharity
        Public Overridable Property AlrahmaCharityTransactions As ICollection(Of AlrahmaCharityTransaction) = New HashSet(Of AlrahmaCharityTransaction)
        Public Overridable Property ZakatProjectsTransactions As ICollection(Of ZakatProjectsTransaction) = New HashSet(Of ZakatProjectsTransaction)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class CharityTransactionsHistory
        Public Property ID As Integer
        Public Property ProjectId As Nullable(Of Integer)
        Public Property SubProjectId As Nullable(Of Integer)
        Public Property Service As String
        Public Property TrackId As Nullable(Of Long)
        Public Property MobileNo As String
        Public Property EmailId As String
        Public Property Amount As String
        Public Property AmntWithCommission As String
        Public Property ServiceResult As String
        Public Property TransactionDate As Nullable(Of Date)
        Public Property LastUpdated As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class CharityUserServiceConfig
        Public Property ID As Integer
        Public Property Username As String
        Public Property Service As String
        Public Property Status As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class CMSUser
        Public Property ID As Integer
        Public Property Username As String
        Public Property Password As String
        Public Property Status As Nullable(Of Boolean)
        Public Property Role As String
        Public Property info1 As String
        Public Property info2 As String
        Public Property LastAccessed As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ConfirmedTpartyTransaction
        Public Property ID As Long
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property Status As String
        Public Property OnDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Denomination
        Public Property ID As Integer
        Public Property ServiceID As String
        Public Property Amount As String
        Public Property Amount2 As String
        Public Property Status As Nullable(Of Boolean)
    
        Public Overridable Property Service As Service
    
    End Class

End Namespace
Namespace Data

    Partial Public Class DPayitTPTransaction
        Public Property ID As Long
        Public Property UserName As String
        Public Property Password As String
        Public Property Type As String
        Public Property IMEIID As Nullable(Of Integer)
        Public Property ServiceCode As String
        Public Property MobileNumber As String
        Public Property Amount As Double
        Public Property ThirdPartyID As String
        Public Property IsysID As String
        Public Property PaymentAPI As String
        Public Property Result As String
        Public Property Status As String
        Public Property Comment As String
        Public Property RetryCount As Byte
        Public Property TranDate As Date
        Public Property ProcessTranDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class DummyPIN
        Public Property ID As Long
        Public Property Serial As String
        Public Property PIN As String
        Public Property EncryptedPIN As Byte()
        Public Property Service As String
        Public Property Amount As Nullable(Of Double)
        Public Property TranDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property Amount2 As String
        Public Property FLAG As String
        Public Property InvoiceNumber As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class EnetService
        Public Property myid As Integer
        Public Property catid As Nullable(Of Integer)
        Public Property catname As String
        Public Property compid As Nullable(Of Integer)
        Public Property compname As String
        Public Property serviceid As Nullable(Of Integer)
        Public Property servicecode As String
        Public Property servicedescription As String
        Public Property serviceTypeID As Nullable(Of Integer)
        Public Property ServiceTypeName As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class FactTable
        Public Property ID As Long
        Public Property UdidID As Nullable(Of Integer)
        Public Property TrackID As Nullable(Of Long)
        Public Property PType As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Mobile As String
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class FraudList
        Public Property ID As Long
        Public Property UdidID As Nullable(Of Integer)
        Public Property Mobile As String
        Public Property Description As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property CreatedBy As String
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property UserType As Nullable(Of Integer)
        Public Property UserValue As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class FraudRule
        Public Property ID As Integer
        Public Property RuleType As Nullable(Of Integer)
        Public Property ConfigID As Nullable(Of Integer)
        Public Property UserType As Nullable(Of Integer)
        Public Property LimitType As Nullable(Of Integer)
        Public Property LimitValue As Nullable(Of Integer)
        Public Property Duration As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedOn As Nullable(Of Date)
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property UpdatedBy As String
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class FraudWhiteList
        Public Property ID As Long
        Public Property UdidID As Nullable(Of Integer)
        Public Property Mobile As String
        Public Property Description As String
        Public Property Status As Nullable(Of Boolean)
        Public Property WhiteListDate As Nullable(Of Date)
        Public Property WhiteListedBy As String
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property UserType As Nullable(Of Integer)
        Public Property UserValue As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class KYCRatingRule
        Public Property ID As Integer
        Public Property RuleType As Nullable(Of Integer)
        Public Property ConfigID As Nullable(Of Integer)
        Public Property LimitType As Nullable(Of Integer)
        Public Property LimitValue As Nullable(Of Integer)
        Public Property Duration As Nullable(Of Integer)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property Status As Boolean
        Public Property UpdateBy As Nullable(Of Integer)
        Public Property Configuration As String
        Public Property KYCRating As Nullable(Of Integer)
        Public Property KYCRatingService As Nullable(Of Integer)
        Public Property KYCRatingTypes As Nullable(Of Integer)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class KYCRatingValidation
        Public Property ID As Integer
        Public Property ValidationType As Nullable(Of Integer)
        Public Property ConfigID As Nullable(Of Integer)
        Public Property MinAmt As Nullable(Of Double)
        Public Property MaxAmt As Nullable(Of Double)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Status As Boolean
        Public Property CreatedOn As Nullable(Of Date)
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property UpdateBy As Nullable(Of Integer)
        Public Property Configuration As String
        Public Property KYCRating As Nullable(Of Integer)
        Public Property KYCRatingService As Nullable(Of Integer)
        Public Property KYCRatingTypes As Nullable(Of Integer)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class KYCType
        Public Property ID As Integer
        Public Property Name As String
        Public Property Description As String
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
        Public Overridable Property PayitServicesKYCTypes As ICollection(Of PayitServicesKYCType) = New HashSet(Of PayitServicesKYCType)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class LogTrace
        Public Property ID As Long
        Public Property Page As String
        Public Property Service As String
        Public Property PaymentChannel As String
        Public Property status As Nullable(Of Boolean)
        Public Property ChangedBy As String
        Public Property info1 As String
        Public Property info2 As String
        Public Property CreatedOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class OperatorsCredit
        Public Property ID As Byte
        Public Property ServiceCode As String
        Public Property PrepaidCredit As Nullable(Of Integer)
        Public Property PostpaidCredit As Nullable(Of Integer)
        Public Property PrepaidReserve As Nullable(Of Short)
        Public Property PostpaidReserve As Nullable(Of Short)
        Public Property Status As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class OperatorsCreditHistory
        Public Property ID As Long
        Public Property PayitiSYSID As Nullable(Of Long)
        Public Property TranDate As Nullable(Of Date)
    
        Public Overridable Property PayitiSY As PayitiSY
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitCategory
        Public Property ID As Integer
        Public Property CategoryName As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property CategoryInfo As String
        Public Property Priority As Nullable(Of Integer)
    
        Public Overridable Property PayitServicesCategories As ICollection(Of PayitServicesCategory) = New HashSet(Of PayitServicesCategory)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItCCLogin
        Public Property ID As Integer
        Public Property userid As String
        Public Property password As String
        Public Property Status As Nullable(Of Boolean)
        Public Property Amount As Nullable(Of Double)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItCCTran
        Public Property ID As Integer
        Public Property userid As String
        Public Property Amount As Nullable(Of Double)
        Public Property isysid As String
        Public Property CreatedDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitCommission
        Public Property ID As Integer
        Public Property ServiceCode As String
        Public Property Denomination As Nullable(Of Double)
        Public Property OperatorCommission As Nullable(Of Double)
        Public Property ADealerCommission As Nullable(Of Double)
        Public Property BDealerCommission As Nullable(Of Double)
        Public Property CDealerCommission As Nullable(Of Double)
        Public Property DDealerCommission As Nullable(Of Double)
        Public Property EDealerCommission As Nullable(Of Double)
        Public Property FDealerCommission As Nullable(Of Double)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitComplaint
        Public Property ID As Integer
        Public Property UDID_ID As Nullable(Of Integer)
        Public Property Name As String
        Public Property EmailID As String
        Public Property MobileNo As String
        Public Property Msg As String
        Public Property Datetime As Nullable(Of Date)
        Public Property Status As String
        Public Property Comments As String
        Public Property Processed_By As String
    
        Public Overridable Property payitcomplaintstracks As ICollection(Of payitcomplaintstrack) = New HashSet(Of payitcomplaintstrack)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitComplaintsSocial
        Public Property ID As Integer
        Public Property UDID_ID As Nullable(Of Long)
        Public Property Name As String
        Public Property EmailID As String
        Public Property MobileNo As String
        Public Property Msg As String
        Public Property Datetime As Nullable(Of Date)
        Public Property Status As String
        Public Property Comments As String
        Public Property Processed_By As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class payitcomplaintstrack
        Public Property ID As Integer
        Public Property ComplaintID As Integer
        Public Property Status As String
        Public Property Comments As String
        Public Property Processed_By As String
        Public Property Created As Nullable(Of Date)
    
        Public Overridable Property PayitComplaint As PayitComplaint
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItCountry
        Public Property ID As Integer
        Public Property Country_En As String
        Public Property Country_Ar As String
        Public Property Country_Code As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property DateTime As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitiSY
        Public Property ID As Long
        Public Property IsysID As Nullable(Of Long)
        Public Property TransactionID As Nullable(Of Long)
        Public Property OperatorOrderID As Nullable(Of Long)
        Public Property MobileNo As String
        Public Property Service As String
        Public Property Amount As Nullable(Of Double)
        Public Property TranDate As Date
        Public Property ProcessTranDate As Nullable(Of Date)
        Public Property ProcessTranDescription As String
        Public Property PaymentAPI As String
    
        Public Overridable Property OperatorsCreditHistories As ICollection(Of OperatorsCreditHistory) = New HashSet(Of OperatorsCreditHistory)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitService
        Public Property ID As Integer
        Public Property ServiceCode As String
        Public Property ServiceName As String
        Public Property ServiceDescription As String
        Public Property Status As Nullable(Of Boolean)
        Public Property KNetPaymentTunnel As String
        Public Property MinAmtThreshold As Nullable(Of Integer)
        Public Property Logo As String
        Public Property Type As String
        Public Property PaymentChannels As String
        Public Property Help As String
        Public Property ServiceNameAR As String
        Public Property ServiceDescriptionAR As String
        Public Property HelpAR As String
        Public Property ServiceOrder As Nullable(Of Integer)
        Public Property StatusNew As Nullable(Of Boolean)
        Public Property LogoNew As String
    
        Public Overridable Property PayitServicesCategories As ICollection(Of PayitServicesCategory) = New HashSet(Of PayitServicesCategory)
        Public Overridable Property PayitServicesConfigs As ICollection(Of PayitServicesConfig) = New HashSet(Of PayitServicesConfig)
        Public Overridable Property PayitServicesKYCTypes As ICollection(Of PayitServicesKYCType) = New HashSet(Of PayitServicesKYCType)
        Public Overridable Property PayitServiceUserKYCs As ICollection(Of PayitServiceUserKYC) = New HashSet(Of PayitServiceUserKYC)
        Public Overridable Property PayitServiceValidations As ICollection(Of PayitServiceValidation) = New HashSet(Of PayitServiceValidation)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServicesCategory
        Public Property ID As Integer
        Public Property PayitCategoryID As Nullable(Of Integer)
        Public Property PayitServicesID As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property PayitServicePriority As Nullable(Of Integer)
    
        Public Overridable Property PayitCategory As PayitCategory
        Public Overridable Property PayitService As PayitService
        Public Overridable Property PayitUserServiceCategories As ICollection(Of PayitUserServiceCategory) = New HashSet(Of PayitUserServiceCategory)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServicesConfig
        Public Property ID As Integer
        Public Property PayitServiceID As Nullable(Of Integer)
        Public Property Commission As String
        Public Property isCommissionMandatory As Nullable(Of Boolean)
        Public Property CommissionInfo As String
        Public Property isAmountEditable As Nullable(Of Boolean)
        Public Property KeypadType As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Info3 As String
        Public Property Info4 As String
    
        Public Overridable Property PayitService As PayitService
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServicesKYCType
        Public Property ID As Integer
        Public Property KYCTypeID As Nullable(Of Integer)
        Public Property PayitServiceID As Nullable(Of Integer)
        Public Property KYCRating As Nullable(Of Integer)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
        Public Overridable Property KYCType As KYCType
        Public Overridable Property PayitService As PayitService
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServicesPaymentsCommission
        Public Property CommissionID As Integer
        Public Property Code As String
        Public Property ServiceCode As String
        Public Property PaymentCode As String
        Public Property CommissionType As String
        Public Property CommissionValue As Nullable(Of Double)
        Public Property Threshold As Nullable(Of Double)
        Public Property ThresholdType As Nullable(Of Integer)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property IsMandatory As Nullable(Of Boolean)
        Public Property CommissionMsg As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServiceUserKYC
        Public Property ID As Integer
        Public Property UserIdentifier As Nullable(Of Long)
        Public Property PayitServiceID As Nullable(Of Integer)
        Public Property KYCRating As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
        Public Overridable Property PayitService As PayitService
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitServiceValidation
        Public Property ID As Long
        Public Property ServiceID As Nullable(Of Integer)
        Public Property IsValidationRequired As Nullable(Of Boolean)
        Public Property IsValidationRequiredForEveryNumber As Nullable(Of Boolean)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property isUSSD As Nullable(Of Boolean)
        Public Property USSDCODE As String
        Public Property Information As String
        Public Property InformationIOS As String
    
        Public Overridable Property PayitService As PayitService
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitUDID
        Public Property ID As Integer
        Public Property UDID As String
        Public Property Status As Nullable(Of Boolean)
        Public Property TranDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitUDID_Restrictions
        Public Property ID As Integer
        Public Property UDID As String
        Public Property Status As Nullable(Of Boolean)
        Public Property TranDate As Nullable(Of Date)
        Public Property DeviceUID As String
        Public Property UserID As Nullable(Of Integer)
        Public Property Version As String
    
        Public Overridable Property user As user
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItUserInfo
        Public Property ID As Integer
        Public Property MobileNo As String
        Public Property ID_UDID As Nullable(Of Integer)
        Public Property CID As Nullable(Of Long)
        Public Property TranDate As Nullable(Of Date)
        Public Property RefMobileNo As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItUserInfo_Restrictions
        Public Property ID As Integer
        Public Property MobileNo As String
        Public Property ID_UDID As Nullable(Of Long)
        Public Property CID As Nullable(Of Long)
        Public Property TranDate As Nullable(Of Date)
        Public Property RefMobileNo As String
        Public Property ServiceCode As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayItUserRestriction
        Public Property ID As Integer
        Public Property MobileNo As String
        Public Property ID_UDID As Nullable(Of Long)
        Public Property TrackID As String
        Public Property TranDate As Nullable(Of Date)
        Public Property ServiceCode As String
        Public Property DeviceID As String
        Public Property Status As Nullable(Of Boolean)
        Public Property StatusDesc As String
        Public Property Amount As String
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PayitUserServiceCategory
        Public Property ID As Integer
        Public Property PayitUserID As Nullable(Of Integer)
        Public Property PayitServiceCategoryID As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
    
        Public Overridable Property PayitServicesCategory As PayitServicesCategory
        Public Overridable Property user As user
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PaymentChannel
        Public Property ID As Short
        Public Property PaymentName As String
        Public Property PaymentLogo As String
        Public Property Status As Boolean
        Public Property StatusForiPhone As Nullable(Of Boolean)
        Public Property StatusNew As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PaymentChannelTunnel
        Public Property ID As Integer
        Public Property PaymentChannel As String
        Public Property TunnelAlias As String
        Public Property TunnelCode As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedOn As Nullable(Of Date)
        Public Property CreatedBy As String
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property UpdatedBy As String
        Public Property Configuration As String
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PIN
        Public Property ID As Long
        Public Property Serial As String
        Public Property PIN1 As String
        Public Property EncryptedPIN As Byte()
        Public Property Service As String
        Public Property Amount As Nullable(Of Double)
        Public Property TranDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property Amount2 As String
        Public Property OrderDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PINPriority
        Public Property ID As Integer
        Public Property Service As String
        Public Property Denomination As String
        Public Property Priority As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PinsAlert
        Public Property ID As Long
        Public Property ServiceCode As String
        Public Property Denomination As String
        Public Property Vendor As String
        Public Property RemainingPINS As Nullable(Of Integer)
        Public Property CretedOn As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Promo
        Public Property ID As Integer
        Public Property Title As String
        Public Property Description As String
        Public Property StartDate As Nullable(Of Date)
        Public Property EndDate As Nullable(Of Date)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property ServiceCode As String
        Public Property Reference As String
        Public Property Url As String
        Public Property Type As String
        Public Property Status As Nullable(Of Boolean)
        Public Property ServiceType As String
        Public Property Priority As Nullable(Of Integer)
        Public Property DisplayAmount As String
        Public Property OfferValue As String
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Info3 As String
        Public Property isTesting As Nullable(Of Boolean)
        Public Property isSingleOffer As Nullable(Of Integer)
        Public Property isSingleOfferV2 As Nullable(Of Integer)
        Public Property ShowInService As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class PushNotificationMessage
        Public Property ID As Integer
        Public Property Message As String
        Public Property Platform As String
        Public Property Language As String
        Public Property Application As String
        Public Property Reference As String
        Public Property MessageCategory As String
        Public Property ScheduledDate As Nullable(Of Date)
        Public Property FinshedDate As Nullable(Of Date)
        Public Property TableReferenceID As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
        Public Property StatusDescription As String
        Public Property CreatedDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class QucikPayMaster
        Public Property ID As Integer
        Public Property TrackID As Nullable(Of Long)
        Public Property UserID As Nullable(Of Long)
        Public Property UDID_ID As Nullable(Of Long)
        Public Property MobileNo As String
        Public Property IP As String
        Public Property AppUsername As String
        Public Property Deviceid As String
        Public Property Ptype As String
        Public Property AppOS As String
        Public Property Status As Nullable(Of Integer)
        Public Property StatusDesc As String
        Public Property Amount As Nullable(Of Double)
        Public Property Commission As Nullable(Of Double)
        Public Property TotalCount As Nullable(Of Integer)
        Public Property SuccessCount As Nullable(Of Integer)
        Public Property FailedCount As Nullable(Of Integer)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property ProcessedOn As Nullable(Of Date)
        Public Property UserEmail As String
        Public Property UserName As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class QuickPayTransaction
        Public Property ID As Long
        Public Property QuickPayTrackID As Nullable(Of Long)
        Public Property TrackID As Nullable(Of Long)
        Public Property ServiceCode As String
        Public Property ServiceAmount As String
        Public Property ServiceStatus As Nullable(Of Integer)
        Public Property ServiceStatusDesc As String
        Public Property Quantity As Nullable(Of Integer)
        Public Property PaymentChannelCode As String
        Public Property PaymentAmount As Nullable(Of Double)
        Public Property PaymentStatus As Nullable(Of Integer)
        Public Property PaymentStatusDesc As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property ProcessedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Integer)
        Public Property StatusDesc As String
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property UserID As Nullable(Of Long)
        Public Property UDID_ID As Nullable(Of Long)
        Public Property MobileNo As String
        Public Property IP As String
        Public Property AppUsername As String
        Public Property AppPassword As String
        Public Property ServiceType As String
        Public Property Deviceid As String
        Public Property Ptype As String
        Public Property AppOs As String
        Public Property DenominationText As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Service
        Public Property ServiceID As String
        Public Property ServiceName As String
        Public Property ID As Integer
    
        Public Overridable Property Denominations As ICollection(Of Denomination) = New HashSet(Of Denomination)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ServicePaymentTunnel
        Public Property ID As Integer
        Public Property ServicePaymentID As Nullable(Of Integer)
        Public Property PaymentChannelTunnelID As Nullable(Of Integer)
        Public Property ThresholdType As Nullable(Of Integer)
        Public Property ThresholdValue As Nullable(Of Double)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedOn As Nullable(Of Date)
        Public Property CreatedBy As String
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property UpdatedBy As String
        Public Property Configuration As String
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ServicesAndPayment
        Public Property ID As Short
        Public Property ServiceCode As String
        Public Property PaymentName As String
        Public Property Status As Boolean
    
        Public Overridable Property ServicesPaymentsCommissions As ICollection(Of ServicesPaymentsCommission) = New HashSet(Of ServicesPaymentsCommission)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ServicesPaymentsCommission
        Public Property CommissionID As Integer
        Public Property ServicePaymentsID As Nullable(Of Short)
        Public Property CommissionType As String
        Public Property CommissionValue As Nullable(Of Double)
        Public Property Threshold As Nullable(Of Double)
        Public Property ThresholdType As Nullable(Of Integer)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
    
        Public Overridable Property ServicesAndPayment As ServicesAndPayment
    
    End Class

End Namespace
Namespace Data

    Partial Public Class SMSPIN
        Public Property ID As Long
        Public Property TrackID As String
        Public Property Message As String
        Public Property ServiceCode As String
        Public Property MobileNo As String
        Public Property MailID As String
        Public Property TranDate As Nullable(Of Date)
        Public Property Status As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class StockDenomination
        Public Property ID As Integer
        Public Property StockRepositoryID As Nullable(Of Integer)
        Public Property Denomination As String
        Public Property Amount As String
        Public Property Vendor As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
        Public Overridable Property StockRepository As StockRepository
    
    End Class

End Namespace
Namespace Data

    Partial Public Class StockMConnect
        Public Property ID As Integer
        Public Property OrderID As String
        Public Property OrderDate As Nullable(Of Date)
        Public Property Status As String
        Public Property CategoryID As String
        Public Property CategoryName As String
        Public Property BrandID As String
        Public Property BrandName As String
        Public Property DenominationID As String
        Public Property DenominationName As String
        Public Property OrderQuantity As String
        Public Property VendorOrderID As String
        Public Property VendorBalance As String
        Public Property Voucher As String
        Public Property TransDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class StockOrder
        Public Property ID As Long
        Public Property Category As String
        Public Property Brand As String
        Public Property Service As String
        Public Property Denomination As String
        Public Property QuantityOrdered As Nullable(Of Integer)
        Public Property Amount As String
        Public Property Amount2 As String
        Public Property QuantityServed As Nullable(Of Integer)
        Public Property Status As String
        Public Property TransDate As Nullable(Of Date)
        Public Property LastUpdated As Nullable(Of Date)
        Public Property MConnectDenom As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class StockRepository
        Public Property ID As Integer
        Public Property category As String
        Public Property brand As String
        Public Property ServiceCode As String
        Public Property ServiceID As Nullable(Of Integer)
        Public Property Status As Nullable(Of Boolean)
    
        Public Overridable Property StockDenominations As ICollection(Of StockDenomination) = New HashSet(Of StockDenomination)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class StockRequestResponse
        Public Property ID As Long
        Public Property StockOrderID As Nullable(Of Long)
        Public Property Request As String
        Public Property Response As String
        Public Property TranDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdParty_knet_trans
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Date
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdParty_knet_trans_20150219
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Nullable(Of Date)
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdParty_knet_trans_20150319
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Nullable(Of Date)
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdParty_knet_trans_20150518
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Nullable(Of Date)
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdParty_knet_trans20150422
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Nullable(Of Date)
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ThirdpartyServiceTransaction
        Public Property Id As Integer
        Public Property AppUser As String
        Public Property AppPass As String
        Public Property TrackId As Nullable(Of Long)
        Public Property Service As String
        Public Property MobileNo As String
        Public Property Amount As String
        Public Property AmntWithCommission As String
        Public Property Quantity As String
        Public Property ServiceResult As String
        Public Property PaymentResult As String
        Public Property ServiceResponse As String
        Public Property TransactionDate As Nullable(Of Date)
        Public Property LastUpdated As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property UserId As Nullable(Of Long)
        Public Property Info3 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Ticket
        Public Property ID As Long
        Public Property TicketId As String
        Public Property RefId As Nullable(Of Long)
        Public Property Customer As String
        Public Property MobileNumber As String
        Public Property EmailId As String
        Public Property Amount As Nullable(Of Double)
        Public Property Service As String
        Public Property PaymentType As String
        Public Property Description As String
        Public Property ComplaintSource As String
        Public Property Title As String
        Public Property Category As String
        Public Property Priority As String
        Public Property RecordedBy As String
        Public Property ProcessedBy As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property Comments As String
        Public Property Status As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class topup_trans
        Public Property myid As Integer
        Public Property usern As String
        Public Property company As String
        Public Property amt As String
        Public Property pamt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transval As Nullable(Of Integer)
        Public Property rawresponse As String
        Public Property errormsg As String
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property knetprocess As String
        Public Property destmob As Nullable(Of Decimal)
        Public Property topupamt As Nullable(Of Integer)
        Public Property topupresult As String
        Public Property topuprawresponse As String
        Public Property tdatetime As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class topuprate
        Public Property myid As Integer
        Public Property Country As String
        Public Property Opr As String
        Public Property product1 As String
        Public Property product As Nullable(Of Integer)
        Public Property pprice As Nullable(Of Double)
        Public Property sprice As Nullable(Of Decimal)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class topupratesnew
        Public Property myid As Integer
        Public Property Country As String
        Public Property Opr As String
        Public Property product1 As String
        Public Property product As Nullable(Of Integer)
        Public Property pprice As Nullable(Of Double)
        Public Property sprice As Nullable(Of Decimal)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Transaction
        Public Property ID As Long
        Public Property UDID As Nullable(Of Integer)
        Public Property UserID As Nullable(Of Long)
        Public Property MobileNumber As String
        Public Property ServiceCode As String
        Public Property PaymentChannel As String
        Public Property Amount As Nullable(Of Double)
        Public Property TransactionStatus As String
        Public Property TransactionDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class Translation
        Public Property ID As Integer
        Public Property LanguageCode As String
        Public Property SourceText As String
        Public Property TranslatedText As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class UpdateUserInfo
        Public Property ID As Long
        Public Property TrackId As String
        Public Property ServiceCode As String
        Public Property Mobile As String
        Public Property Tdatetime As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class user
        Public Property myid As Integer
        Public Property company As String
        Public Property auser As String
        Public Property apass As String
        Public Property mob As String
        Public Property acc_type As String
        Public Property acc_status As String
        Public Property dates As String
        Public Property times As String
    
        Public Overridable Property PayitUDID_Restrictions As ICollection(Of PayitUDID_Restrictions) = New HashSet(Of PayitUDID_Restrictions)
        Public Overridable Property PayitUserServiceCategories As ICollection(Of PayitUserServiceCategory) = New HashSet(Of PayitUserServiceCategory)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class UserFavourite
        Public Property ID As Integer
        Public Property UserIdentifier As Nullable(Of Long)
        Public Property ServiceName As String
        Public Property ServiceCode As String
        Public Property PaymentChannelName As String
        Public Property PaymentChannelCode As String
        Public Property Amount As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class UserTransaction
        Public Property ID As Integer
        Public Property TrackID As Nullable(Of Integer)
        Public Property UserIdentifier As Nullable(Of Long)
        Public Property Amount As Nullable(Of Double)
        Public Property ServiceAmount As Nullable(Of Double)
        Public Property Currency As String
        Public Property ServiceCurrency As String
        Public Property ServiceName As String
        Public Property ServiceCode As String
        Public Property PaymentChannelCode As String
        Public Property PaymentChannelName As String
        Public Property ProcessDate As Nullable(Of Date)
        Public Property UserMobileNumber As String
        Public Property MobileNumber As String
        Public Property ServiceReference As String
        Public Property PaymentReference As String
        Public Property TransactionType As String
        Public Property TransactionDescription As String
        Public Property TransactionStatus As String
        Public Property Quantity As Nullable(Of Integer)
        Public Property TotalAmount As Nullable(Of Double)
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property LastUpdatedOn As Nullable(Of Date)
        Public Property Reference1 As String
        Public Property Reference2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ZakatProject
        Public Property ID As Integer
        Public Property ZakatProjectName As String
        Public Property Description As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property Priority As Nullable(Of Integer)
    
        Public Overridable Property ZakatProjectsTransactions As ICollection(Of ZakatProjectsTransaction) = New HashSet(Of ZakatProjectsTransaction)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ZakatProjectsTransaction
        Public Property ID As Integer
        Public Property ZakatProjectID As Nullable(Of Integer)
        Public Property MobileNumber As String
        Public Property EmailID As String
        Public Property Amount As String
        Public Property TransactionStatus As String
        Public Property TrackID As String
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Status As Nullable(Of Boolean)
        Public Property SubprojectId As Nullable(Of Integer)
    
        Public Overridable Property ZakatProject As ZakatProject
        Public Overridable Property CharitySubProject As CharitySubProject
    
    End Class

End Namespace
Namespace Data

    Partial Public Class AddUpdateCustomer_Result
        Public Property ID As Integer
        Public Property UDID_ID As Nullable(Of Integer)
        Public Property Name As String
        Public Property EmailID As String
        Public Property MobileNo As String
        Public Property Msg As String
        Public Property Datetime As Nullable(Of Date)
        Public Property Status As String
        Public Property Comments As String
        Public Property Processed_By As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class fnSplitString_Result
        Public Property splitdata As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetAgentStats_Result
        Public Property ProcessedBy As String
        Public Property Open As Integer
        Public Property Active As Integer
        Public Property Pending As Integer
        Public Property Closed As Integer
        Public Property TOGCC As Integer
        Public Property NoStatus As Integer
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetComplaintAudit_Result
        Public Property ID As Long
        Public Property TicketId As String
        Public Property RefId As Nullable(Of Long)
        Public Property Customer As String
        Public Property MobileNumber As String
        Public Property EmailId As String
        Public Property Amount As Nullable(Of Double)
        Public Property Service As String
        Public Property PaymentType As String
        Public Property Description As String
        Public Property ComplaintSource As String
        Public Property Title As String
        Public Property Category As String
        Public Property Priority As String
        Public Property RecordedBy As String
        Public Property ProcessedBy As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property Comments As String
        Public Property Status As String
        Public Property OldValues As String
        Public Property NewValues As String
        Public Property ModifiedBy As String
        Public Property RoleId As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetInternationalCountryList_Result
        Public Property country_en As String
        Public Property country_ar As String
        Public Property Country_Code As Nullable(Of Integer)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetInternationalProductList_Result
        Public Property product As Nullable(Of Integer)
        Public Property sprice As Nullable(Of Decimal)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetPINDeominations_Result
        Public Property Amount As Nullable(Of Double)
        Public Property Amount2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetPINDeominationstest_Result
        Public Property Amount As Nullable(Of Double)
        Public Property Amount2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class GetReprocessAudit_Result
        Public Property ID As Long
        Public Property Userid As Nullable(Of Integer)
        Public Property Action As String
        Public Property TicketId As String
        Public Property OldValues As String
        Public Property NewValues As String
        Public Property UserName As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property ModifiedOn As Nullable(Of Date)
        Public Property RoleId As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class InsertEnetOldtoNew_Result
        Public Property myid As Integer
        Public Property company As String
        Public Property Tuser As String
        Public Property Tpass As String
        Public Property Tresponse_link As String
        Public Property TId As Long
        Public Property IsysId As String
        Public Property amt As String
        Public Property ptype As String
        Public Property trackid As Nullable(Of Long)
        Public Property payid As Nullable(Of Decimal)
        Public Property transid As Nullable(Of Decimal)
        Public Property refid As Nullable(Of Decimal)
        Public Property postdate As Nullable(Of Integer)
        Public Property knetprocess As String
        Public Property rawresponse As String
        Public Property errmsg As String
        Public Property udf1 As String
        Public Property udf2 As String
        Public Property udf3 As String
        Public Property udf4 As String
        Public Property udf5 As String
        Public Property tdatetime As Nullable(Of Date)
        Public Property LastUpdateOn As Nullable(Of Date)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class MyPaymentCustomerRegister_PendingTransactions_Result
        Public Property OrderID As Long
        Public Property Amount As Nullable(Of Double)
        Public Property OrderDate As Nullable(Of Date)
        Public Property MerchantName As String
        Public Property OrderReference As String
        Public Property OrderDescription As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class MyPaymentCustomerRegister_TransactionsHistory_Result
        Public Property OrderID As Long
        Public Property Amount As Nullable(Of Double)
        Public Property OrderDate As Nullable(Of Date)
        Public Property ProcessedDate As Nullable(Of Date)
        Public Property MerchantName As String
        Public Property OrderReference As String
        Public Property OrderStatus As String
        Public Property OrderDescription As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ProcessFailedPIN2_Result
        Public Property isysid As String
        Public Property udf3 As String
        Public Property udf2 As String
        Public Property amt As String
        Public Property Column1 As String
        Public Property Column2 As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class ProcessFailedPinNew_Result
        Public Property PIN As String
        Public Property Serial As String
        Public Property Status As String
        Public Property Amount As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class sp_helpdiagramdefinition_Result
        Public Property version As Nullable(Of Integer)
        Public Property definition As Byte()
    
    End Class

End Namespace
Namespace Data

    Partial Public Class sp_helpdiagrams_Result
        Public Property Database As String
        Public Property Name As String
        Public Property ID As Integer
        Public Property Owner As String
        Public Property OwnerID As Integer
    
    End Class

End Namespace
Namespace Data

    Partial Public Class USP_Get_Action_Privileges_Result
        Public Property parentid As Nullable(Of Integer)
        Public Property sortorder As Nullable(Of Integer)
        Public Property menuorder As Nullable(Of Integer)
        Public Property menuid As Integer
        Public Property roleid As Integer
        Public Property menutitle As String
        Public Property rolename As String
        Public Property CanAdd As String
        Public Property CanEdit As String
        Public Property CanView As String
        Public Property CanReprocess As String
        Public Property CanMarkasSettled As String
        Public Property CanReprocessByEdit As String
        Public Property ParentMenuName As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class USP_GetProcessedByName_Result
        Public Property Amount As Nullable(Of Double)
        Public Property Category As String
        Public Property Comments As String
        Public Property ComplaintSource As String
        Public Property CreatedOn As Nullable(Of Date)
        Public Property Customer As String
        Public Property Description As String
        Public Property EmailId As String
        Public Property ID As Long
        Public Property MobileNumber As String
        Public Property PaymentType As String
        Public Property Priority As String
        Public Property RecordedBy As String
        Public Property RefId As Nullable(Of Long)
        Public Property Service As String
        Public Property Status As String
        Public Property ProcessedBy As String
        Public Property TicketId As String
        Public Property Title As String
        Public Property UpdatedOn As Nullable(Of Date)
        Public Property UserName As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class USP_GetServices_Result
        Public Property serviceCode As String
        Public Property ServiceName As String
    
    End Class

End Namespace
