'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Data

    Partial Public Class SanctionsList
        Public Property ID As Integer
        Public Property FullName As String
        Public Property DOBDate As Nullable(Of Integer)
        Public Property DOBMonth As Nullable(Of Integer)
        Public Property DOBYear As Nullable(Of Integer)
        Public Property Nationality As String
        Public Property CountryCode As String
        Public Property PassportNo As String
        Public Property NationalIdentityNumber As String
        Public Property Address As String
        Public Property Status As Boolean
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Info3 As String
        Public Property Info4 As String
        Public Property Source As String
        Public Property SourceDocInformation As String
        Public Property SourceID As String
    
    End Class

End Namespace
Namespace Data

    Partial Public Class WalletAccount
        Public Property ID As Long
        Public Property WalletID As Nullable(Of Long)
        Public Property WalletTypeID As Nullable(Of Integer)
        Public Property UserIdentifier As Nullable(Of Long)
        Public Property UseCustomerLogin As Boolean
        Public Property SMSAuthenticatedTransaction As Nullable(Of Boolean)
        Public Property CVVAuthentcatedTransaction As String
        Public Property Username As String
        Public Property Password As String
        Public Property Balance As Nullable(Of Double)
        Public Property Currency As String
        Public Property Status As Boolean
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property Info3 As String
        Public Property Info4 As String
        Public Property AccountNumber As String
        Public Property WalletTypeCountryID As Nullable(Of Integer)
        Public Property isActive As Boolean
        Public Property [Alias] As String
        Public Property isFirstLogin As Boolean
        Public Property FirstLoginDate As Nullable(Of Date)
    
        Public Overridable Property WalletTransactions As ICollection(Of WalletTransaction) = New HashSet(Of WalletTransaction)
    
    End Class

End Namespace
Namespace Data

    Partial Public Class WalletTransaction
        Public Property ID As Long
        Public Property APPID As Nullable(Of Integer)
        Public Property WalletAccountID As Nullable(Of Long)
        Public Property ProfileID As Nullable(Of Long)
        Public Property WalletTypeID As Nullable(Of Integer)
        Public Property UserIdentifier As Nullable(Of Long)
        Public Property TrackID As Nullable(Of Long)
        Public Property TransactionType As String
        Public Property TransactionRef As String
        Public Property UserMobile As String
        Public Property UserEmail As String
        Public Property TransactionDate As Nullable(Of Date)
        Public Property PaymentService As String
        Public Property PaymentServiceName As String
        Public Property PaymentReference As String
        Public Property PaymentAccountType As String
        Public Property PaymentStatusDescription As String
        Public Property Amount As Nullable(Of Double)
        Public Property TransactionAmount As Nullable(Of Double)
        Public Property Currency As String
        Public Property TransactionCurrency As String
        Public Property TransactionStatus As String
        Public Property Status As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property Info1 As String
        Public Property Info2 As String
        Public Property SenderName As String
        Public Property RecieverName As String
        Public Property Commission As Nullable(Of Double)
    
        Public Overridable Property WalletAccount As WalletAccount
    
    End Class

End Namespace
